/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.cuongdz.javaasm.View;

import com.cuongdz.javaasm.Controller.ManageCourse;
import com.cuongdz.javaasm.Model.MySQLUtility;
import com.cuongdz.javaasm.Model.UserIO;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class AddToCourse extends javax.swing.JDialog {

    private int studentid;
    private String courseid;
    ManageCourse mc = new ManageCourse();
    /**
     * Creates new form AddToCourse
     *
     * @param parent
     * @param studentid
     */
    public AddToCourse(java.awt.Frame parent, int studentid) {
        super(parent, true);
        initComponents();
        getClassItem();
        this.studentid = studentid;
    }

    private void getClassItem() {
        ResultSet rs = MySQLUtility.getTCTable();
        try {
            while (rs.next()) {
                courseid = rs.getString("tc.courseid");
                cboClass.addItem(rs.getString("tc.TCID") + "- " + rs.getString("c.Name") + " " + rs.getString("tc.DateCreated"));
            }
        } catch (Exception ex) {

        }
    }

    private String getClassSelectedID(String s) {
        if (cboClass.getSelectedIndex() > 0) {
            return s.substring(0, s.indexOf("-"));
        } else {
            return "";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboClass = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        lbNotify = new javax.swing.JLabel();
        lbNumber = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add to Class");
        setResizable(false);

        cboClass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--" }));
        cboClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboClassActionPerformed(evt);
            }
        });

        jLabel1.setText("In Class:");

        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNotify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(39, 39, 39)
                                .addComponent(lbNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cboClass, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboClass, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lbNotify, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboClassActionPerformed
        // TODO add your handling code here:
        if (cboClass.getSelectedIndex() > 0) {
            lbNumber.setText(MySQLUtility.getNumberStudentInClass(UserIO.getSelectedID(cboClass)) + "/40");
        } else {
            lbNumber.setText("");
        }
    }//GEN-LAST:event_cboClassActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        // Check selected index
        if (cboClass.getSelectedIndex() < 1) {
            lbNotify.setText("Please Select!");
            return;
        }
        // Check class room availibility
        if (!mc.isClassEnoughSpace(UserIO.getSelectedID(cboClass))) {
            lbNotify.setText("Class full!");
            return;
        }
        // Check student already in class
        if(MySQLUtility.isInClass(UserIO.getSelectedID(cboClass), studentid)){
            lbNotify.setText("Student already in this class!");
            return;
        }else{
        // Update to database
        MySQLUtility.addToClass(UserIO.getSelectedID(cboClass), studentid,courseid);
        JOptionPane.showMessageDialog(null, "Add Successfully!");     
        }

        this.dispose();
    }//GEN-LAST:event_btnConfirmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<String> cboClass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbNotify;
    private javax.swing.JLabel lbNumber;
    // End of variables declaration//GEN-END:variables
}
