package com.cuongdz.javaasm.View;

import com.cuongdz.javaasm.Controller.ManageCourse;
import com.cuongdz.javaasm.Controller.TableDisplay;
import com.cuongdz.javaasm.Model.MySQLUtility;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;

/**
 *
 * @author Cuongdz
 */
public class CoursesPage extends javax.swing.JDialog {

    TableDisplay td;
    ManageCourse mc = new ManageCourse();

    /**
     * Creates new form NewJDialog1
     */
    public CoursesPage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        td = new TableDisplay();

        td.generateStudentsCoursesTable(tbSC);
        td.generateTeachersCoursesTable(tbTC);
        getClassItem();
    }

    private void getClassItem() {
        ResultSet rs = MySQLUtility.getTable("teachers_courses");
        try {
            while (rs.next()) {
                cboClass.addItem(rs.getString("TCID"));
            }
        } catch (Exception ex) {

        }
    }

    public void deleteClass() {
        int idx = tbTC.getSelectedRow();
        if (idx <= 0) {
            JOptionPane.showMessageDialog(null, "Please select row!");

            return;
        }
        int id = Integer.parseInt(tbTC.getValueAt(idx, 0) + "");
        if (JOptionPane.showConfirmDialog(null, "Are you Sure?") != JOptionPane.OK_OPTION) {
            return;
        }
        mc.deleteClass(id);
        reload();
    }

    public void removeStudent() {
        int idx = tbSC.getSelectedRow();
        if (idx <= 0) {
            JOptionPane.showMessageDialog(null, "Please select row!");
            return;
        }
        int cid = Integer.parseInt(tbSC.getValueAt(idx, 0) + "");
        int sid = Integer.parseInt(tbSC.getValueAt(idx, 1) + "");
        mc.removeStudent(cid, sid);
    }

    public void getInfo() {
        int idx = tbTC.getSelectedRow();
        if (idx <= 0) {
            JOptionPane.showMessageDialog(null, "Please select row!");
            return;
        }

        int id = Integer.parseInt(tbTC.getValueAt(idx, 0) + "");
        int number = MySQLUtility.getNumberStudentInClass(id);
        JOptionPane.showMessageDialog(null, "Class: " + id + "\n" + number + "/40");

    }

    private void reload() {
        td.generateStudentsCoursesTable(tbSC);
        td.generateTeachersCoursesTable(tbTC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTC = new javax.swing.JTable();
        btnReload = new javax.swing.JButton();
        btnAddSC = new javax.swing.JButton();
        btnInfoTC = new javax.swing.JButton();
        btnDeleteSC = new javax.swing.JButton();
        btnDeleteTC = new javax.swing.JButton();
        txtSearchSC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSC = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cboClass = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Class Management");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Student Courses ");

        tbTC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbTC.getTableHeader().setReorderingAllowed(false);
        tbTC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTCMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbTC);

        btnReload.setText("Reload");
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });

        btnAddSC.setText("Add");
        btnAddSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSCActionPerformed(evt);
            }
        });

        btnInfoTC.setText("Info");
        btnInfoTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoTCActionPerformed(evt);
            }
        });

        btnDeleteSC.setText("Delete");
        btnDeleteSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSCActionPerformed(evt);
            }
        });

        btnDeleteTC.setText("Delete");
        btnDeleteTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTCActionPerformed(evt);
            }
        });

        txtSearchSC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchSCKeyReleased(evt);
            }
        });

        tbSC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbSC.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbSC);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Classes");

        cboClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--" }));
        cboClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(38, 38, 38))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cboClass, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDeleteTC, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(btnReload)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnAddSC, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDeleteSC, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnInfoTC, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchSC, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboClass, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearchSC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAddSC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDeleteSC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnInfoTC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnReload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDeleteTC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        // TODO add your handling code here:
        reload();
    }//GEN-LAST:event_btnReloadActionPerformed

    private void btnAddSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSCActionPerformed
        // TODO add your handling code here:
        AddClass ac = new AddClass(null, true);
        ac.setLocationRelativeTo(null);
        ac.setVisible(true);
    }//GEN-LAST:event_btnAddSCActionPerformed

    private void btnInfoTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoTCActionPerformed
        // TODO add your handling code here:
        getInfo();
    }//GEN-LAST:event_btnInfoTCActionPerformed

    private void btnDeleteSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSCActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Are you Sure ?") != JOptionPane.OK_OPTION) {
            return;
        }
        deleteClass();
        reload();
    }//GEN-LAST:event_btnDeleteSCActionPerformed

    private void btnDeleteTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTCActionPerformed
        // TODO add your handling code here:
        removeStudent();
        reload();
    }//GEN-LAST:event_btnDeleteTCActionPerformed

    private void txtSearchSCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchSCKeyReleased
        // TODO add your handling code here:
        td.sorter1.setRowFilter(RowFilter.regexFilter("(?i)" + txtSearchSC.getText().trim()));
    }//GEN-LAST:event_txtSearchSCKeyReleased

    private void cboClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboClassActionPerformed

        String key = cboClass.getSelectedItem() + "";
        td.sorter.setRowFilter(RowFilter.regexFilter("^" + key + "$", 0));

    }//GEN-LAST:event_cboClassActionPerformed

    private void tbTCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTCMouseClicked
        // TODO add your handling code here:
        int idx = tbTC.getSelectedRow();
        String key = tbTC.getValueAt(idx, 0) + "";
        if (idx > -1) {
            td.sorter.setRowFilter(RowFilter.regexFilter("^" + key + "$", 0));
        }
    }//GEN-LAST:event_tbTCMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSC;
    private javax.swing.JButton btnDeleteSC;
    private javax.swing.JButton btnDeleteTC;
    private javax.swing.JButton btnInfoTC;
    private javax.swing.JButton btnReload;
    private javax.swing.JComboBox<String> cboClass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbSC;
    private javax.swing.JTable tbTC;
    private javax.swing.JTextField txtSearchSC;
    // End of variables declaration//GEN-END:variables
}
